// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/votes.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vote struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CountryVotedFor     string                 `protobuf:"bytes,1,opt,name=country_voted_for,json=countryVotedFor,proto3" json:"country_voted_for,omitempty"`
	CountryVotedForName string                 `protobuf:"bytes,2,opt,name=country_voted_for_name,json=countryVotedForName,proto3" json:"country_voted_for_name,omitempty"`
	VoteCount           int32                  `protobuf:"varint,3,opt,name=vote_count,json=voteCount,proto3" json:"vote_count,omitempty"`
	VoterCountry        string                 `protobuf:"bytes,4,opt,name=voter_country,json=voterCountry,proto3" json:"voter_country,omitempty"`
	VoterCountryName    string                 `protobuf:"bytes,5,opt,name=voter_country_name,json=voterCountryName,proto3" json:"voter_country_name,omitempty"`
	Timestamp           int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SongId              int32                  `protobuf:"varint,7,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	SongName            string                 `protobuf:"bytes,8,opt,name=song_name,json=songName,proto3" json:"song_name,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Vote) Reset() {
	*x = Vote{}
	mi := &file_proto_votes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vote) ProtoMessage() {}

func (x *Vote) ProtoReflect() protoreflect.Message {
	mi := &file_proto_votes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vote.ProtoReflect.Descriptor instead.
func (*Vote) Descriptor() ([]byte, []int) {
	return file_proto_votes_proto_rawDescGZIP(), []int{0}
}

func (x *Vote) GetCountryVotedFor() string {
	if x != nil {
		return x.CountryVotedFor
	}
	return ""
}

func (x *Vote) GetCountryVotedForName() string {
	if x != nil {
		return x.CountryVotedForName
	}
	return ""
}

func (x *Vote) GetVoteCount() int32 {
	if x != nil {
		return x.VoteCount
	}
	return 0
}

func (x *Vote) GetVoterCountry() string {
	if x != nil {
		return x.VoterCountry
	}
	return ""
}

func (x *Vote) GetVoterCountryName() string {
	if x != nil {
		return x.VoterCountryName
	}
	return ""
}

func (x *Vote) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Vote) GetSongId() int32 {
	if x != nil {
		return x.SongId
	}
	return 0
}

func (x *Vote) GetSongName() string {
	if x != nil {
		return x.SongName
	}
	return ""
}

type VoteStreamRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IncludeHistorical bool                   `protobuf:"varint,1,opt,name=include_historical,json=includeHistorical,proto3" json:"include_historical,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VoteStreamRequest) Reset() {
	*x = VoteStreamRequest{}
	mi := &file_proto_votes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteStreamRequest) ProtoMessage() {}

func (x *VoteStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_votes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteStreamRequest.ProtoReflect.Descriptor instead.
func (*VoteStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_votes_proto_rawDescGZIP(), []int{1}
}

func (x *VoteStreamRequest) GetIncludeHistorical() bool {
	if x != nil {
		return x.IncludeHistorical
	}
	return false
}

type SongVoteData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SongId        int32                  `protobuf:"varint,1,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	SongName      string                 `protobuf:"bytes,2,opt,name=song_name,json=songName,proto3" json:"song_name,omitempty"`
	CountryId     string                 `protobuf:"bytes,3,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	CountryName   string                 `protobuf:"bytes,4,opt,name=country_name,json=countryName,proto3" json:"country_name,omitempty"`
	PublicVotes   int32                  `protobuf:"varint,5,opt,name=public_votes,json=publicVotes,proto3" json:"public_votes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SongVoteData) Reset() {
	*x = SongVoteData{}
	mi := &file_proto_votes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SongVoteData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongVoteData) ProtoMessage() {}

func (x *SongVoteData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_votes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongVoteData.ProtoReflect.Descriptor instead.
func (*SongVoteData) Descriptor() ([]byte, []int) {
	return file_proto_votes_proto_rawDescGZIP(), []int{2}
}

func (x *SongVoteData) GetSongId() int32 {
	if x != nil {
		return x.SongId
	}
	return 0
}

func (x *SongVoteData) GetSongName() string {
	if x != nil {
		return x.SongName
	}
	return ""
}

func (x *SongVoteData) GetCountryId() string {
	if x != nil {
		return x.CountryId
	}
	return ""
}

func (x *SongVoteData) GetCountryName() string {
	if x != nil {
		return x.CountryName
	}
	return ""
}

func (x *SongVoteData) GetPublicVotes() int32 {
	if x != nil {
		return x.PublicVotes
	}
	return 0
}

type GetSongsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSongsRequest) Reset() {
	*x = GetSongsRequest{}
	mi := &file_proto_votes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSongsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSongsRequest) ProtoMessage() {}

func (x *GetSongsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_votes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSongsRequest.ProtoReflect.Descriptor instead.
func (*GetSongsRequest) Descriptor() ([]byte, []int) {
	return file_proto_votes_proto_rawDescGZIP(), []int{3}
}

type GetSongsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Songs         []*SongVoteData        `protobuf:"bytes,1,rep,name=songs,proto3" json:"songs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSongsResponse) Reset() {
	*x = GetSongsResponse{}
	mi := &file_proto_votes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSongsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSongsResponse) ProtoMessage() {}

func (x *GetSongsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_votes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSongsResponse.ProtoReflect.Descriptor instead.
func (*GetSongsResponse) Descriptor() ([]byte, []int) {
	return file_proto_votes_proto_rawDescGZIP(), []int{4}
}

func (x *GetSongsResponse) GetSongs() []*SongVoteData {
	if x != nil {
		return x.Songs
	}
	return nil
}

var File_proto_votes_proto protoreflect.FileDescriptor

const file_proto_votes_proto_rawDesc = "" +
	"\n" +
	"\x11proto/votes.proto\x12\x05votes\"\xad\x02\n" +
	"\x04Vote\x12*\n" +
	"\x11country_voted_for\x18\x01 \x01(\tR\x0fcountryVotedFor\x123\n" +
	"\x16country_voted_for_name\x18\x02 \x01(\tR\x13countryVotedForName\x12\x1d\n" +
	"\n" +
	"vote_count\x18\x03 \x01(\x05R\tvoteCount\x12#\n" +
	"\rvoter_country\x18\x04 \x01(\tR\fvoterCountry\x12,\n" +
	"\x12voter_country_name\x18\x05 \x01(\tR\x10voterCountryName\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x17\n" +
	"\asong_id\x18\a \x01(\x05R\x06songId\x12\x1b\n" +
	"\tsong_name\x18\b \x01(\tR\bsongName\"B\n" +
	"\x11VoteStreamRequest\x12-\n" +
	"\x12include_historical\x18\x01 \x01(\bR\x11includeHistorical\"\xa9\x01\n" +
	"\fSongVoteData\x12\x17\n" +
	"\asong_id\x18\x01 \x01(\x05R\x06songId\x12\x1b\n" +
	"\tsong_name\x18\x02 \x01(\tR\bsongName\x12\x1d\n" +
	"\n" +
	"country_id\x18\x03 \x01(\tR\tcountryId\x12!\n" +
	"\fcountry_name\x18\x04 \x01(\tR\vcountryName\x12!\n" +
	"\fpublic_votes\x18\x05 \x01(\x05R\vpublicVotes\"\x11\n" +
	"\x0fGetSongsRequest\"=\n" +
	"\x10GetSongsResponse\x12)\n" +
	"\x05songs\x18\x01 \x03(\v2\x13.votes.SongVoteDataR\x05songs2\x8b\x01\n" +
	"\vVoteService\x126\n" +
	"\vStreamVotes\x12\x18.votes.VoteStreamRequest\x1a\v.votes.Vote0\x01\x12D\n" +
	"\x11GetSongsWithVotes\x12\x16.votes.GetSongsRequest\x1a\x17.votes.GetSongsResponseB\fZ\n" +
	"main/protob\x06proto3"

var (
	file_proto_votes_proto_rawDescOnce sync.Once
	file_proto_votes_proto_rawDescData []byte
)

func file_proto_votes_proto_rawDescGZIP() []byte {
	file_proto_votes_proto_rawDescOnce.Do(func() {
		file_proto_votes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_votes_proto_rawDesc), len(file_proto_votes_proto_rawDesc)))
	})
	return file_proto_votes_proto_rawDescData
}

var file_proto_votes_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_votes_proto_goTypes = []any{
	(*Vote)(nil),              // 0: votes.Vote
	(*VoteStreamRequest)(nil), // 1: votes.VoteStreamRequest
	(*SongVoteData)(nil),      // 2: votes.SongVoteData
	(*GetSongsRequest)(nil),   // 3: votes.GetSongsRequest
	(*GetSongsResponse)(nil),  // 4: votes.GetSongsResponse
}
var file_proto_votes_proto_depIdxs = []int32{
	2, // 0: votes.GetSongsResponse.songs:type_name -> votes.SongVoteData
	1, // 1: votes.VoteService.StreamVotes:input_type -> votes.VoteStreamRequest
	3, // 2: votes.VoteService.GetSongsWithVotes:input_type -> votes.GetSongsRequest
	0, // 3: votes.VoteService.StreamVotes:output_type -> votes.Vote
	4, // 4: votes.VoteService.GetSongsWithVotes:output_type -> votes.GetSongsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_votes_proto_init() }
func file_proto_votes_proto_init() {
	if File_proto_votes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_votes_proto_rawDesc), len(file_proto_votes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_votes_proto_goTypes,
		DependencyIndexes: file_proto_votes_proto_depIdxs,
		MessageInfos:      file_proto_votes_proto_msgTypes,
	}.Build()
	File_proto_votes_proto = out.File
	file_proto_votes_proto_goTypes = nil
	file_proto_votes_proto_depIdxs = nil
}
