# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: votes.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'votes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvotes.proto\x12\x05votes\"\xbf\x01\n\x04Vote\x12\x19\n\x11\x63ountry_voted_for\x18\x01 \x01(\t\x12\x1e\n\x16\x63ountry_voted_for_name\x18\x02 \x01(\t\x12\x12\n\nvote_count\x18\x03 \x01(\x05\x12\x15\n\rvoter_country\x18\x04 \x01(\t\x12\x1a\n\x12voter_country_name\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\x12\x0f\n\x07song_id\x18\x07 \x01(\x05\x12\x11\n\tsong_name\x18\x08 \x01(\t\"/\n\x11VoteStreamRequest\x12\x1a\n\x12include_historical\x18\x01 \x01(\x08\x32\x45\n\x0bVoteService\x12\x36\n\x0bStreamVotes\x12\x18.votes.VoteStreamRequest\x1a\x0b.votes.Vote0\x01\x42\x0cZ\nmain/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'votes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\nmain/proto'
  _globals['_VOTE']._serialized_start=23
  _globals['_VOTE']._serialized_end=214
  _globals['_VOTESTREAMREQUEST']._serialized_start=216
  _globals['_VOTESTREAMREQUEST']._serialized_end=263
  _globals['_VOTESERVICE']._serialized_start=265
  _globals['_VOTESERVICE']._serialized_end=334
# @@protoc_insertion_point(module_scope)
