apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: esc-voting
spec:
  serviceName: loki
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.9.6
          args: ["-config.file=/etc/loki/local-config.yaml"]
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: loki-data
              mountPath: /loki
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 512Mi
  volumeClaimTemplates:
    - metadata:
        name: loki-data
      spec:
        storageClassName: local-path
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: esc-voting
spec:
  selector:
    app: loki
  ports:
    - port: 3100
      targetPort: 3100
